;;; package --- Summary
;;; Commentary:
;;; Code:

;;;;;;;;
;; keymapping personalization
;;;;;;;;

(if (or (eq system-type 'gnu/linux) (eq system-type 'darwin))
    (set-face-attribute 'default nil :height 140)
  )

;; disable the window-up/window down feature of shift-arrows so that
;; shift-selection works with arrow keys.
(define-key global-map (kbd "<S-down>") nil)
(define-key global-map (kbd "<S-up>") nil)
(define-key global-map (kbd "<S-right>") nil)
(define-key global-map (kbd "<S-left>") nil)

;; Stuff to map common Mac keystrokes to emacs operations
(setq-default mac-command-modifier 'super)
(setq-default mac-option-modifier 'meta)
(define-key global-map (kbd "s-a") 'mark-whole-buffer)
(define-key global-map (kbd "s-c") 'ns-copy-including-secondary)
;; (define-key global-map (kbd "C-s") 'helm-swoop)
(setq helm-source-names-using-follow (quote ("RTags Helm")))

(define-key global-map (kbd "C-x C-f") 'find-file-at-point)
(if (not (eq system-type 'windows-nt))
    (define-key global-map (kbd "<f12>") 'rtags-fix-fixit-at-point)
  )

(global-set-key [(f6)] 'next-error)


(defun my-switch-to-compilation-and-recompile ()
  "Switch to the *compilation* buffer and run `recompile`."
  (interactive)
  (let ((compilation-buffer (get-buffer "*compilation*")))
    (if compilation-buffer
        (progn
          (switch-to-buffer compilation-buffer)
          (recompile))
      (message "No *compilation* buffer found."))))
;; Bind the function to F5
(global-set-key (kbd "<f5>") #'my-switch-to-compilation-and-recompile)

;; Code navigation & debugging key maps
(require 'gud)
(global-set-key [(f9)] 'rtags-compile-file)
(global-set-key [(f10)] 'gud-next)
(global-set-key [(f11)] 'gud-step)
(global-set-key [(shift f11)] 'gud-finish)
(global-set-key (kbd "s-f") 'helm-projectile-find-file)
(global-set-key (kbd "<S-left>") 'xref-pop-marker-stack)
(global-set-key (kbd "s-.") 'xref-pop-marker-stack)

;;;;;;;;
;; Whitespace
;;;;;;;;
;; activate whitespace-mode to view all whitespace characters
(global-set-key (kbd "C-c w") 'whitespace-mode)
;; show unncessary whitespace that can mess up your diff
(add-hook 'prog-mode-hook (lambda () (interactive) (setq show-trailing-whitespace 1)))
;; use space to indent by default
(setq-default indent-tabs-mode nil)

;;;;;;;;
;; Indentation
;;;;;;;;
(c-set-offset 'substatement-open 0)
;; other customizations can go here

(setq-default c-default-style "stroustrup"
              c-basic-offset 4
              c++-tab-always-indent t
              c-indent-level 4
              tab-width 4
              standard-indent 4
              )

(setq tab-stop-list '(4 8 12 16 20 24 28 32 36 40 44 48 52 56 60))

;;;;;;;;
;; Scrolling & Window handling
;;;;;;;;
(setq-default scroll-conservatively 5)
(setq-default truncate-lines 1)
(setq-default split-height-threshold 0) ;; Make windows always split vertically
(setq-default split-width-threshold nil) ;; Make windows always split vertically

(scroll-bar-mode 0)
(menu-bar-mode 0)
(tool-bar-mode 0)

;;;;;;;;
;; Extension mode mapping
;;;;;;;;
(add-to-list 'auto-mode-alist '("\\.h\\'" . c++-mode))
(add-to-list 'auto-mode-alist '("\\.m\\'" . c++-mode))
(add-to-list 'auto-mode-alist '("\\.mm\\'" . c++-mode))

;;;;;;;;
;; Mode replacements
;;;;;;;;
;; Use silver searcher (ag) instead of grep for recursive searching
(setq grep-command "ag --vimgrep --group --line-number --column --smart-case --stats -- ")
(setq inhibit-startup-message t) ;; hide the startup message
;; (global-linum-mode t) ;; enable line numbers globally

;; ;; needed to suppress stupid "unsafe directory" messages when
;; ;; using magit
;; (require 'server)
;; (when (and (>= emacs-major-version 23)
;;            (equal window-system 'w32))
;;   (defun server-ensure-safe-dir (dir) "Noop" t)) ; Suppress error "directory
;;                                                  ; ~/.emacs.d/server is unsafe"
;;                                                  ; on windows.
;; (server-start)

;; (require 'server)
;;  (and (>= emacs-major-version 23)
;;      (defun server-ensure-safe-dir (dir) "Noop" t))


;;;;;;;;
;; Honor color generated by build tools in compilation buffers
;;;;;;;;
(setq-default compilation-environment (add-to-list 'compilation-environment "TERM=xterm-256color"))
(setq-default compilation-environment (add-to-list 'compilation-environment (concat "LIBRARY_PATH=" (getenv "LIBRARY_PATH"))))
(setq-default compilation-environment (add-to-list 'compilation-environment (concat "PATH=" (getenv "PATH"))))
(setq-default compilation-environment (add-to-list 'compilation-environment (concat "LD_LIBRARY_PATH=" (getenv "LD_LIBRARY_PATH"))))

(setq-default compilation-environment (add-to-list 'compilation-environment (concat "AFFDEX_DATA_DIR=" (getenv "AFFDEX_DATA_DIR"))))
(setq-default compilation-environment (add-to-list 'compilation-environment (concat "AFFDEX_TESTDATA_DIR=" (getenv "AFFDEX_TESTDATA_DIR"))))
(setq-default compilation-environment (add-to-list 'compilation-environment (concat "CMAKE_ATTRIBS_ARGS=" (getenv "CMAKE_ATTRIBS_ARGS"))))

(setq-default compilation-environment (add-to-list 'compilation-environment (concat "AFFECTIVA_VISION_DATA_DIR=" (getenv "AFFECTIVA_VISION_DATA_DIR"))))
(setq-default compilation-environment (add-to-list 'compilation-environment (concat "AFFECTIVA_LOG_MODULES=" (getenv "AFFECTIVA_LOG_MODULES"))))
(setq-default compilation-environment (add-to-list 'compilation-environment (concat "AFFECTIVA_LOG_LEVEL=" (getenv "AFFECTIVA_LOG_LEVEL"))))
(setq-default compilation-environment (add-to-list 'compilation-environment (concat "AFFECTIVA_LOG_TO=" (getenv "AFFECTIVA_LOG_TO"))))

(setq-default compilation-environment (add-to-list 'compilation-environment (concat "TENSORFLOW_VERSION=" (getenv "TENSORFLOW_VERSION"))))

(ignore-errors
  (require 'ansi-color)
  (defun my-colorize-compilation-buffer ()
    (when (eq major-mode 'compilation-mode)
      (ansi-color-apply-on-region compilation-filter-start (point-max))))
  (add-hook 'compilation-filter-hook 'my-colorize-compilation-buffer))


;;;;;;;;
;; custom functions
;;;;;;;;

;; (require 'iedit)

(defun smb-make-named-parms ()
  "Convert a bindParam from ordered to using substitution variable."
  (interactive)
  (progn
    (iedit-quit)
    (search-forward-regexp "bindParam([^\"]")
    (left-char 1)
    (search-forward-regexp "[a-zA-Z]")
    (left-char 1)
    (set-mark-command nil)
    (search-forward-regexp "[^a-zA-Z]")
    (left-char 1)
    (copy-region-as-kill 1 1 1)
    (search-backward "(")
    (right-char 1)
    (insert "\"@")
    (yank)
    (insert "\", ")
    (goto-char 0)
    (search-forward "?")
    (delete-char -1)
    (insert "@")
    (yank)
    (set-mark-command nil)
    (search-backward "@")
    (iedit-mode 0)
    (right-word)
    (recenter)
    )
  )
;;(global-set-key [(f8)] 'smb-make-named-parms)


;;;;;;;;;
;; Major mode key binding overrides
;;;;;;;;;
(defvar my-keys-minor-mode-map
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "C-x v l") 'magit-log-buffer-file)
    map)
  "Keymap for my-keys-minor-mode.")

(define-minor-mode my-keys-minor-mode
  "A minor mode so that my key settings override annoying major modes."
  :init-value t
  :lighter " my-keys")

(my-keys-minor-mode 1)

(defun my-minibuffer-setup-hook ()
  "Hook for deactivating my minibuffer-setup."
  (my-keys-minor-mode 0))

(add-hook 'minibuffer-setup-hook 'my-minibuffer-setup-hook)

(load "carb")

;;;;;;;;
;; Open sqlite files with ebdi
;;;;;;;;

;; (defun smb-open-sqlite-hook ()
;;   "An open hook that will invoke ebdi when opening sqlite files."
;;   (let ((sql-database buffer-file-truename))
;;     (when (and  (stringp sql-database)
;;                 (or    (string-match "\\.sqlite$" sql-database)
;;                        (string-match "\\.db$" sql-database)))
;;       (message (concat "opening " sql-database " using ebdi-sqlite"))
;;       (kill-buffer)
;;      ;; (sql-sqlite sql-database)
;;       (edbi-sqlite sql-database)
;;       )))

;; (add-hook 'find-file-hook 'smb-open-sqlite-hook)

;; (defun sqlite-handler (operation &rest args)
;;   "An open hook that will invoke ebdi when opening sqlite files."
;;   (let ((sql-database (car args)))
;;     (kill-buffer nil)
;;     (edbi-sqlite sql-database)
;;     (sql-sqlite sql-database)
;;     )
;;   )

;; (put 'sqlite-handler 'operations '(insert-file-contents))

;; (add-to-list 'file-name-handler-alist
;;              '("\\.sqlite\\|\\.db\\|\\.DB\\'" . sqlite-handler))

(global-subword-mode)

(add-to-list 'auto-mode-alist '("\\.cu\\'" . c++-mode))

;;;;;;
;; Disable display of super-annoying gdb output buffer that forces code into new frame
;;;;;;
(setq-default gdb-display-io-nopopup 1)

(defun python3 ()
    "Start python3."
  (interactive)
  (run-python "python3" 1 0)
  )

(setq-default ediff-window-setup-function 'ediff-setup-windows-plain)

(defun run-bash ()
      (interactive)
      (let ((shell-file-name "c:/Users/brobesx/AppData/Local/Programs/Git/bin/bash.exe"))
            (shell "*bash*")))

(setq visible-bell t)

(global-auto-revert-mode)
(global-ligature-mode)


(setq-default blacken-executable-list '("py" "-m" "black"))

;;;;;;
;; Visual Studio enhancements
;;;;;;

(if (eq system-type 'windows-nt)
    (progn
      (defun find-directory-of-file-in-ancestor (extension)
        "Find a file with the given EXTENSION in an ancestor directory."
        (locate-dominating-file default-directory
                                           (lambda (dir)
                                             (directory-files dir nil (concat ".*\\." extension "$")))))

      (defun find-file-in-ancestor (extension)
        "List all files in DIR with the given EXTENSION."
         (car (directory-files (find-directory-of-file-in-ancestor extension) t (concat ".*\\." extension "$"))))

      ;; Create a string that is "MSBuild " <find-file-in-ancestor> " /property"
        (defun visual-studio-build-solution ()
            (interactive)
            (let ((solution (find-file-in-ancestor "sln")))
            (if solution
                (funcall 'compile (concat "MSBuild \"" solution "\" /property:Configuration=Release /property:Platform=x64 /p:SelectedFiles=m6drv.cpp"))
                (message "No solution file found in ancestor directories."))))

        (global-set-key (kbd "<C-f5>") 'visual-studio-build-solution)
      )
  )

(minions-mode)

(defun compile-msbuild-file ()
  "Uses MSBuild to compile current buffer"
  (interactive)
  (let* ((current-file (buffer-file-name))
         (dir (file-name-directory current-file))
         (vcxproj (car (directory-files dir t "\\.vcxproj$")))
         (file-name (file-name-nondirectory current-file)))
    (if vcxproj
        (let ((compile-command
               (format "MSBuild /v:m \"%s\" /t:ClCompile /property:Configuration=Release /property:Platform=x64 /p:SelectedFiles=\"%s\""
                       vcxproj file-name)))
          (compile compile-command))
      (message "No .vcxproj file found in the current directory."))))

(defun compile-msbuild-project ()
  "Use MSBuild to compile current project."
  (interactive)
  (let* ((current-file (buffer-file-name))
         (dir (file-name-directory current-file))
         (vcxproj (car (directory-files dir t "\\.vcxproj$")))
         (file-name (file-name-nondirectory current-file)))
    (if vcxproj
        (let ((compile-command
               (format "MSBuild /v:m \"%s\" /t:ClCompile /property:Configuration=Release /property:Platform=x64 -maxcpucount"
                       vcxproj file-name)))
          (compile compile-command))
      (message "No .vcxproj file found in the current directory."))))

(defun msbuild-project ()
  "Use MSBuild to compile current project."
  (interactive)
  (let* ((current-file (buffer-file-name))
         (dir (file-name-directory current-file))
         (vcxproj (car (directory-files dir t "\\.vcxproj$")))
         (file-name (file-name-nondirectory current-file)))
    (if vcxproj
        (let ((compile-command
               (format "MSBuild /v:m \"%s\" /property:Configuration=Release /property:Platform=x64 -maxcpucount"
                       vcxproj file-name)))
          (compile compile-command))
      (message "No .vcxproj file found in the current directory."))))

(global-set-key [(ctrl f7)] 'compile-msbuild-file)
(global-set-key [(shift f7)] 'compile-msbuild-project)
(global-set-key [(f7)] 'msbuild-project)

;; Clang for windows error recognition:

;; Define regexp for Clang Windows error format: filepath(line,column): error: message

;; Define regexp for Clang Windows error format: filepath(line,column): error: message
;; Using separate regexps for errors, warnings, and notes to ensure proper coloring
(add-to-list 'compilation-error-regexp-alist-alist
             '(clang-windows-error
               "^\\([A-Za-z]:[^:()]+\\)(\\([0-9]+\\),\\([0-9]+\\)): \\(fatal \\)?error: \\(.*\\)$"
               1 2 3 2))  ; 2 = error severity (red)

(add-to-list 'compilation-error-regexp-alist-alist
             '(clang-windows-warning
               "^\\([A-Za-z]:[^:]+\\)(\\([0-9]+\\),\\([0-9]+\\)): warning[ A-Za-z0-9]*: \\(.*\\)$"
               1 2 3 1))  ; 1 = warning severity (orange/yellow)

(add-to-list 'compilation-error-regexp-alist-alist
             '(clang-windows-note
               "^\\([A-Za-z]:[^:()]+\\)(\\([0-9]+\\),\\([0-9]+\\)): note: \\(.*\\)$"
               1 2 3 0))  ; 0 = info severity (blue/green)

(add-to-list 'compilation-error-regexp-alist-alist
             '(clang-windows-note
               "^ +\\([A-Za-z]:[^:()]+cpp\\)(\\([0-9]+\\),\\([0-9]+\\)):\\(.*\\)$"
               1 2 3 0))  ; 0 = info severity (blue/green)

;; Enable the new regexps
(add-to-list 'compilation-error-regexp-alist 'clang-windows-error)
(add-to-list 'compilation-error-regexp-alist 'clang-windows-warning)
(add-to-list 'compilation-error-regexp-alist 'clang-windows-note)

;; Optional: Make compilation more user-friendly
(setq compilation-scroll-output 'first-error)
(setq compilation-window-height 15)


(defun copy-current-function-name ()
  "Copy the name of the C++ function at point to the kill ring."
  (interactive)
  (let ((fn-name (which-function)))
    (if fn-name
        (progn
          (kill-new fn-name)
          (message "Copied function name: %s" fn-name))
      (message "No function name found."))))


;; Optional: Ensure proper error face coloring (uncomment if needed)
;; (custom-set-faces
;;  '(compilation-error ((t (:foreground "red" :weight bold))))
;;  '(compilation-warning ((t (:foreground "orange" :weight bold))))
;;  '(compilation-info ((t (:foreground "blue" :weight bold))))))

;;; smb-options.el ends here
