;;; el-get-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from el-get.el

(autoload 'el-get-version "el-get"
"Message the current el-get version" t)
(autoload 'el-get-install "el-get"
"Cause the named PACKAGE to be installed after all of its
dependencies (if any).

PACKAGE may be either a string or the corresponding symbol.

(fn PACKAGE)" t)
(autoload 'el-get-update "el-get"
"Update PACKAGE.

(fn PACKAGE)" t)
(autoload 'el-get-update-all "el-get"
"Performs update of all installed packages.

(fn &optional NO-PROMPT)" t)
(autoload 'el-get-update-packages-of-type "el-get"
"Update all installed packages of type TYPE.

(fn TYPE)" t)
(autoload 'el-get-self-update "el-get"
"Update el-get itself.  The standard recipe takes care of reloading the code." t)
(autoload 'el-get-remove "el-get"
"Remove any PACKAGE that is know to be installed or required.

(fn PACKAGE)" t)
(autoload 'el-get-reinstall "el-get"
"Remove PACKAGE and then install it again.

(fn PACKAGE)" t)
(autoload 'el-get-cd "el-get"
"Open dired in the package directory.

(fn PACKAGE)" t)
(autoload 'el-get-make-recipes "el-get"
"Loop over `el-get-sources' and write a recipe file for each
entry which is not a symbol and is not already a known recipe.

(fn &optional DIR)" t)
(autoload 'el-get-checksum "el-get"
"Compute the checksum of the given package, and put it in the kill-ring

(fn PACKAGE)" t)
(autoload 'el-get-self-checksum "el-get"
"Compute the checksum of the running version of el-get itself.

Also put the checksum in the kill-ring." t)
(autoload 'el-get "el-get"
"Ensure that packages have been downloaded once and init them as needed.

This will not update the sources by using `apt-get install\\=' or
`git pull\\=', but it will ensure that:

* the packages have been installed
* load-path is set so their elisp files can be found
* Info-directory-list is set so their info files can be found
* Autoloads have been prepared and evaluated for each package
* Any post-installation setup (e.g. `(require \\='feature)\\=') happens

When SYNC is nil (the default), all installations run
concurrently, in the background.

When SYNC is \\='sync, each package will be installed synchronously,
and any error will stop it all.

Please note that the `el-get-init\\=' part of `el-get\\=' is always
done synchronously. There\\='s `byte-compile\\=' support though, and
the packages you use are welcome to use `autoload\\=' too.

PACKAGES is expected to be a list of packages you want to install
or init.  When PACKAGES is omited (the default), the list of
already installed packages is considered.

(fn &optional SYNC &rest PACKAGES)")
(register-definition-prefixes "el-get" '("el-get-"))


;;; Generated autoloads from el-get-autoloading.el

(register-definition-prefixes "el-get-autoloading" '("el-get-"))


;;; Generated autoloads from el-get-build.el

(register-definition-prefixes "el-get-build" '("el-get-"))


;;; Generated autoloads from el-get-bundle.el

(autoload 'el-get-bundle-el-get "el-get-bundle"
"

(fn SRC SYNC)")
(autoload 'el-get-bundle "el-get-bundle"
"Install PACKAGE and run initialization FORM.

PACKAGE can be either a simple package name or a package name
with a modifier before the name to specify local recipe source
information:

* `<owner>/' : specifies a Github owner name
* `gist:<id>' : specifies a Gist ID
* `<type>:' : specifies a type of the package source

If `FEATURE in PACKAGE' form is used instead of PACKAGE, then
that FEATURE is `require'd after installing PACKAGE.  You can
also use `el-get-bundle!' macro if FEATURE and PACKAGE are the
same.  If you wish to `require' more than one feature, then use
`:features' property in FORM.

The initialization FORM may start with a property list that
describes a local recipe.  The property list may include the keyword
`:bundle-sync' with a value of either `t' or `nil' to request that
`el-get-bundle' invoke `el-get' synchronously (respectively asynchronously).
The keyword `:bundle-async' is the inverse of `:bundle-sync'.
(Note that the request to run el-get synchronously may not be respected in all
circumstances: see the definition of `el-get-bundle-el-get' for details.)
The FORM after the property list is treated as initialization code,
which is actually an `:after' property of the local recipe.

A copy of the initialization code is stored in a directory
specified by `el-get-bundle-init-directory' and its byte-compiled
version is used if `el-get-bundle-byte-compile' is non-nil.

(fn PACKAGE &rest FORM)" nil t)
(autoload 'el-get-bundle! "el-get-bundle"
"Install PACKAGE and run initialization form.
It is the same as `el-get-bundle' except that PACKAGE is explicitly
required.

(fn PACKAGE &rest ARGS)" nil t)
(register-definition-prefixes "el-get-bundle" '("el-get-bundle-"))


;;; Generated autoloads from el-get-byte-compile.el

(register-definition-prefixes "el-get-byte-compile" '("el-get-"))


;;; Generated autoloads from el-get-check.el

(autoload 'el-get-check-recipe "el-get-check"
"Check the format of the recipe.
Please run this command before sending a pull request.
Usage: M-x el-get-check-recipe RET

You can run this function from checker script like this:
    test/check-recipe.el PATH/TO/RECIPE.rcp

When used as a lisp function, FILE-OR-BUFFER must be a buffer
object or a file path.

(fn FILE-OR-BUFFER)" t)
(register-definition-prefixes "el-get-check" '("el-get-check-"))


;;; Generated autoloads from el-get-core.el

(register-definition-prefixes "el-get-core" '("el-get-"))


;;; Generated autoloads from el-get-custom.el

(register-definition-prefixes "el-get-custom" '("el-get-"))


;;; Generated autoloads from el-get-dependencies.el

(register-definition-prefixes "el-get-dependencies" '("el-get-"))


;;; Generated autoloads from el-get-list-packages.el

(autoload 'el-get-list-packages "el-get-list-packages"
"Display a list of packages." t)
(register-definition-prefixes "el-get-list-packages" '("el-get-"))


;;; Generated autoloads from el-get-notify.el

(register-definition-prefixes "el-get-notify" '("el-get-"))


;;; Generated autoloads from el-get-recipes.el

(register-definition-prefixes "el-get-recipes" '("el-get-"))


;;; Generated autoloads from el-get-status.el

(register-definition-prefixes "el-get-status" '("el-get-"))

;;; End of scraped data

(provide 'el-get-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; el-get-autoloads.el ends here
