;;; helm-projectile-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from helm-projectile.el

(defvar helm-projectile-fuzzy-match t
"Enable fuzzy matching for Helm Projectile commands.
This needs to be set before loading helm-projectile.el.")
(custom-autoload 'helm-projectile-fuzzy-match "helm-projectile" t)
(autoload 'helm-projectile-switch-project "helm-projectile" nil t)
(autoload 'helm-projectile-switch-project-other-window "helm-projectile" nil t)
(autoload 'helm-projectile-switch-project-other-frame "helm-projectile" nil t)
(autoload 'helm-projectile-switch-project-other-tab "helm-projectile" nil t)
(autoload 'helm-projectile-find-file "helm-projectile" nil t)
(autoload 'helm-projectile-find-file-other-window "helm-projectile" nil t)
(autoload 'helm-projectile-find-file-other-frame "helm-projectile" nil t)
(autoload 'helm-projectile-find-file-other-tab "helm-projectile" nil t)
(autoload 'helm-projectile-find-file-in-known-projects "helm-projectile" nil t)
(autoload 'helm-projectile-find-dir "helm-projectile" nil t)
(autoload 'helm-projectile-find-dir-other-window "helm-projectile" nil t)
(autoload 'helm-projectile-find-dir-other-frame "helm-projectile" nil t)
(autoload 'helm-projectile-find-dir-other-tab "helm-projectile" nil t)
(autoload 'helm-projectile-recentf "helm-projectile" nil t)
(autoload 'helm-projectile-switch-to-buffer "helm-projectile" nil t)
(autoload 'helm-projectile-switch-to-buffer-other-window "helm-projectile" nil t)
(autoload 'helm-projectile-switch-to-buffer-other-frame "helm-projectile" nil t)
(autoload 'helm-projectile-find-file-streaming "helm-projectile" nil t)
(autoload 'helm-projectile-find-file-dwim "helm-projectile"
"Find file at point based on context." t)
(autoload 'helm-projectile-find-file-dwim-other-window "helm-projectile"
"Find file at point based on context." t)
(autoload 'helm-projectile-find-file-dwim-other-frame "helm-projectile"
"Find file at point based on context." t)
(autoload 'helm-projectile-find-other-file "helm-projectile"
"Switch between files with the same name but different extensions using Helm.
With FLEX-MATCHING, match any file that contains the base name of
current file.  Other file extensions can be customized with the
variable `projectile-other-file-alist'.

(fn &optional FLEX-MATCHING)" t)
(autoload 'helm-projectile-find-other-file-other-window "helm-projectile"
"Switch between files with the same name but different extensions using Helm.
With FLEX-MATCHING, match any file that contains the base name of
current file.  Other file extensions can be customized with the
variable `projectile-other-file-alist'.

(fn &optional FLEX-MATCHING)" t)
(autoload 'helm-projectile-find-other-file-other-frame "helm-projectile"
"Switch between files with the same name but different extensions using Helm.
With FLEX-MATCHING, match any file that contains the base name of
current file.  Other file extensions can be customized with the
variable `projectile-other-file-alist'.

(fn &optional FLEX-MATCHING)" t)
(autoload 'helm-projectile-on "helm-projectile"
"Turn on `helm-projectile-mode'.
This function is obsolete; use `helm-projectile-mode' instead." t)
(make-obsolete 'helm-projectile-on 'helm-projectile-mode "1.7.0")
(autoload 'helm-projectile-off "helm-projectile"
"Turn off `helm-projectile-mode'.
This function is obsolete; use `helm-projectile-mode' instead." t)
(make-obsolete 'helm-projectile-off 'helm-projectile-mode "1.7.0")
(autoload 'helm-projectile-grep "helm-projectile"
"Helm version of `projectile-grep'.
DIR is the project root, if not set then current project root is used.
FILES is a list of file patterns to search in.  When called with a
prefix argument then ask for FILES.

(fn &optional DIR FILES)" t)
(autoload 'helm-projectile-ack "helm-projectile"
"Run an ack search in the current project with Helm.
DIR directory where to search, if not set then current project root is
used.  TYPES is a list of types to include in search.  When called with
a prefix argument, then ask for TYPES.

This command is obsolete: ack has been superseded by ripgrep and the
silver searcher, and Projectile itself has dropped `projectile-ack'.
Use `helm-projectile-rg' or `helm-projectile-ag' instead.

(fn &optional DIR TYPES)" t)
(autoload 'helm-projectile-ag "helm-projectile"
"Helm version of `projectile-ag'.
When called with a single or a triple prefix argument, ask for OPTIONS.
When called with a double or a triple prefix argument, ask for
TYPES (see `helm-grep-ag').'

This command uses `helm-grep-ag' to perform the search, so the actual
searcher used is determined by the value of `helm-grep-ag-command'.

(fn &optional OPTIONS)" t)
(autoload 'helm-projectile-rg "helm-projectile"
"Projectile version of `helm-rg'.
When package `helm-rg' is not installed and `helm-grep-ag-command' is
pointing to ripgrep (rg) then use `helm-projectile-ag'.  Otherwise if
`helm-projectile-ask-to-install-helm-rg' is non nil then ask to install
package `helm-rg'." t)
(defconst helm-projectile--command-remaps '((projectile-find-other-file . helm-projectile-find-other-file) (projectile-find-other-file-other-window . helm-projectile-find-other-file-other-window) (projectile-find-other-file-other-frame . helm-projectile-find-other-file-other-frame) (projectile-find-file . helm-projectile-find-file) (projectile-find-file-other-window . helm-projectile-find-file-other-window) (projectile-find-file-other-frame . helm-projectile-find-file-other-frame) (projectile-find-file-in-known-projects . helm-projectile-find-file-in-known-projects) (projectile-find-file-dwim . helm-projectile-find-file-dwim) (projectile-find-file-dwim-other-window . helm-projectile-find-file-dwim-other-window) (projectile-find-file-dwim-other-frame . helm-projectile-find-file-dwim-other-frame) (projectile-find-dir . helm-projectile-find-dir) (projectile-find-dir-other-window . helm-projectile-find-dir-other-window) (projectile-find-dir-other-frame . helm-projectile-find-dir-other-frame) (projectile-switch-project . helm-projectile-switch-project) (projectile-recentf . helm-projectile-recentf) (projectile-switch-to-buffer . helm-projectile-switch-to-buffer) (projectile-switch-to-buffer-other-window . helm-projectile-switch-to-buffer-other-window) (projectile-switch-to-buffer-other-frame . helm-projectile-switch-to-buffer-other-frame) (projectile-grep . helm-projectile-grep) (projectile-ag . helm-projectile-ag) (projectile-ripgrep . helm-projectile-rg))
"Alist mapping Projectile commands to their `helm-projectile' replacements.
`helm-projectile-toggle' installs and removes these as command remaps on
`projectile-mode-map'.  The `switch-project' other-window/other-frame
commands are handled separately because they need a compatibility
fallback.")
(defvar helm-projectile-mode nil
"Non-nil if Helm-Projectile mode is enabled.
See the `helm-projectile-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `helm-projectile-mode'.")
(custom-autoload 'helm-projectile-mode "helm-projectile" nil)
(autoload 'helm-projectile-mode "helm-projectile"
"Toggle the Helm version of Projectile commands.

When enabled, remap Projectile's file, directory, buffer and search
commands to their Helm-Projectile equivalents on `projectile-mode-map',
and install the advice and key binding Helm-Projectile relies on.
Disabling removes all of them.

This is a global minor mode.  If called interactively, toggle the
`Helm-Projectile mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='helm-projectile-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'helm-projectile "helm-projectile"
"Use projectile with Helm instead of ido.

With a prefix ARG invalidates the cache first.
If invoked outside of a project, displays a list of known projects to jump.

(fn &optional ARG)" t)
(with-eval-after-load 'projectile (define-key projectile-command-map (kbd "h") #'helm-projectile))
(register-definition-prefixes "helm-projectile" '("helm-"))

;;; End of scraped data

(provide 'helm-projectile-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-projectile-autoloads.el ends here
