;;; dumber-jump-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from dumber-jump.el

(autoload 'dumber-jump-xref-activate "dumber-jump"
"Function to activate xref backend.
Add this function to `xref-backend-functions' to dumber jump to be
activiated, whenever it finds a project. It is recommended to add
it to the end, so that it only gets activated when no better
option is found.")
(register-definition-prefixes "dumber-jump" '("dumber-jump-"))

;;; End of scraped data

(provide 'dumber-jump-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; dumber-jump-autoloads.el ends here
