;;; flymake-json-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flymake-json.el

(autoload 'flymake-json-load "flymake-json"
"Configure flymake mode to check the current buffer's javascript syntax." t)
(autoload 'flymake-json-maybe-load "flymake-json"
"Call `flymake-json-load' if this file appears to be json." t)
(register-definition-prefixes "flymake-json" '("flymake-json-"))

;;; End of scraped data

(provide 'flymake-json-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flymake-json-autoloads.el ends here
